// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResponderClient is the client API for Responder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResponderClient interface {
	// Sends a response
	Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type responderClient struct {
	cc grpc.ClientConnInterface
}

func NewResponderClient(cc grpc.ClientConnInterface) ResponderClient {
	return &responderClient{cc}
}

func (c *responderClient) Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Responder/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResponderServer is the server API for Responder service.
// All implementations must embed UnimplementedResponderServer
// for forward compatibility
type ResponderServer interface {
	// Sends a response
	Invoke(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedResponderServer()
}

// UnimplementedResponderServer must be embedded to have forward compatible implementations.
type UnimplementedResponderServer struct {
}

func (UnimplementedResponderServer) Invoke(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedResponderServer) mustEmbedUnimplementedResponderServer() {}

// UnsafeResponderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResponderServer will
// result in compilation errors.
type UnsafeResponderServer interface {
	mustEmbedUnimplementedResponderServer()
}

func RegisterResponderServer(s grpc.ServiceRegistrar, srv ResponderServer) {
	s.RegisterService(&Responder_ServiceDesc, srv)
}

func _Responder_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponderServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Responder/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponderServer).Invoke(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Responder_ServiceDesc is the grpc.ServiceDesc for Responder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Responder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Responder",
	HandlerType: (*ResponderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Responder_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
